# Generated by Django 5.0.2 on 2024-04-13 12:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import merchants.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_alter_business_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergen',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cuisine',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='restaurantproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shopproduct',
            options={},
        ),
        migrations.RemoveField(
            model_name='businessreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
        migrations.AddField(
            model_name='allergen',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='allergen',
            name='image',
            field=models.ImageField(default=None, upload_to='allergen_images/'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='image',
            field=models.ImageField(default=None, upload_to='cuisine_images/'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='image',
            field=models.ImageField(default=None, upload_to='pb_images/'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default=None, upload_to='pc_images/'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='gstin',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='businessaddress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='businessdocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='businessimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='businesslogo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ownerdocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='review_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), merchants.models.validate_image_dimensions])),
                ('is_trashed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.review')),
            ],
        ),
    ]
