# Generated by Django 5.0.2 on 2024-03-03 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_alter_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='alt_contact_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='business',
            name='alt_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='gstin',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ownerdocument',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='merchants.business'),
        ),
    ]
