# Generated by Django 5.0.2 on 2024-04-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_alter_allergen_options_alter_cuisine_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_data',
            field=models.TextField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
