# Generated by Django 5.0.2 on 2024-03-04 08:46

import django.core.validators
import merchants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_business_alt_contact_number_business_alt_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdocument',
            name='document',
            field=models.FileField(upload_to='business_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='businessimage',
            name='image',
            field=models.ImageField(upload_to='business_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), merchants.models.validate_image_dimensions]),
        ),
        migrations.AlterField(
            model_name='ownerdocument',
            name='document',
            field=models.FileField(upload_to='owner_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_variant',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), merchants.models.validate_image_dimensions]),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size_unit',
            field=models.CharField(choices=[('ml', 'Milliliter'), ('kg', 'Kilogram'), ('large', 'Large'), ('medium', 'Medium'), ('small', 'Small'), ('half', 'Half'), ('full', 'Full'), ('other', 'Other')], default='ml', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_variant',
            field=models.ManyToManyField(to='merchants.productvariation'),
        ),
    ]
