# Generated by Django 5.0.2 on 2024-04-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_alter_product_description_alter_product_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='description',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='description',
            field=models.TextField(default='', max_length=4000),
        ),
    ]
