# Generated by Django 5.0.2 on 2024-04-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_alter_allergen_description_alter_cuisine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('fruit_vegetable', 'Fruit & Vegetable'), ('dairy', 'Dairy'), ('gadgets', 'Gadgets'), ('garage', 'Garage'), ('restaurant', 'Restaurant'), ('sweet_bakery', 'Sweet & Bakery'), ('medical', 'Medical Store'), ('grocery', 'Grocery Store'), ('beauty', 'Beauty Products'), ('electronics', 'Electronics'), ('books', 'Books'), ('toys', 'Toys'), ('sports', 'Sports & Outdoors'), ('pet_supplies', 'Pet Supplies'), ('home_decoration', 'Home Decoration'), ('automotive', 'Automotive'), ('jewellery', 'Jewellery'), ('health_fitness', 'Health & Fitness'), ('music', 'Music'), ('video_games', 'Video Games'), ('furniture', 'Furniture'), ('office_supplies', 'Office Supplies'), ('other', 'Other'), ('na', 'Not Available')], default='other', max_length=20),
        ),
    ]
