# Generated by Django 5.0.2 on 2024-04-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0006_alter_product_name_alter_productcategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopproduct',
            old_name='brand',
            new_name='brands',
        ),
    ]
