# Generated by Django 5.0.2 on 2024-04-21 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0008_alter_restaurantproduct_preparation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='merchants.business'),
        ),
    ]
