# Generated by Django 5.0.2 on 2024-05-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0010_alter_productimage_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(choices=[('indian', 'Indian'), ('chinese', 'Chinese'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('japanese', 'Japanese'), ('american', 'American'), ('thai', 'Thai'), ('french', 'French'), ('spanish', 'Spanish'), ('greek', 'Greek'), ('korean', 'Korean'), ('vietnamese', 'Vietnamese'), ('german', 'German'), ('brazilian', 'Brazilian'), ('levantine', 'Levantine'), ('caribbean', 'Caribbean'), ('moroccan', 'Moroccan'), ('australian', 'Australian'), ('argentinian', 'Argentinian'), ('ethiopian', 'Ethiopian'), ('turkish', 'Turkish'), ('russian', 'Russian'), ('iranian', 'Iranian'), ('lebanese', 'Lebanese'), ('pakistani', 'Pakistani'), ('bangladeshi', 'Bangladeshi'), ('sri_lankan', 'Sri Lankan'), ('nepalese', 'Nepalese'), ('afghan', 'Afghan'), ('various', 'Various'), ('international', 'International'), ('other', 'Other'), ('na', 'Not Available')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('fruit_vegetable', 'Fruit & Vegetable'), ('dairy', 'Dairy'), ('gadgets', 'Gadgets'), ('garage', 'Garage'), ('restaurant', 'Restaurant'), ('sweet_bakery', 'Sweet & Bakery'), ('medical', 'Medical Store'), ('grocery', 'Grocery Store'), ('beauty', 'Beauty Products'), ('electronics', 'Electronics'), ('books', 'Books'), ('toys', 'Toys'), ('sports', 'Sports & Outdoors'), ('pet_supplies', 'Pet Supplies'), ('home_decoration', 'Home Decoration'), ('automotive', 'Automotive'), ('jewellery', 'Jewellery'), ('health_fitness', 'Health & Fitness'), ('music', 'Music'), ('video_games', 'Video Games'), ('furniture', 'Furniture'), ('office_supplies', 'Office Supplies'), ('desserts', 'Desserts'), ('snacks', 'Snacks'), ('spices', 'Spices'), ('ready_to_eat', 'Ready To Eat'), ('vegeterian', 'Vegeterian'), ('non_vegeterian', 'Non Vegeterian'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size_unit',
            field=models.CharField(choices=[('ml', 'Milliliter'), ('kg', 'Kilogram'), ('large', 'Large'), ('medium', 'Medium'), ('small', 'Small'), ('half', 'Half'), ('full', 'Full'), ('other', 'Other'), ('quantity', 'Quantity'), ('na', 'Not Available')], default='other', max_length=20),
        ),
    ]
