# Generated by Django 5.0.2 on 2024-05-22 12:48

import django.core.validators
import merchants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0011_alter_cuisine_name_alter_productcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='default.png', upload_to='product_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), merchants.models.validate_image_dimensions]),
        ),
    ]
